/**
 * Generates the site's theme CSS from a WhileUI preset.
 *
 * This exists to prove one claim from ROADMAP.md end to end: the token layer is
 * renderer-agnostic. Nothing here imports React, React Native, or Uniwind — it
 * reads `theme-presets.ts` (which reads `theme-contract.ts` and
 * `visual-token-contract.ts`, both renderer-free) and writes plain CSS.
 *
 * It does NOT use `themePresetToCss()`. That helper emits `@variant light` /
 * `@variant dark`, which are Uniwind constructs; plain Tailwind 4 has a `dark`
 * variant but no `light` one. So this walks the same variable maps and emits
 * the conventional `:root` + `.dark` form instead. Same tokens, different
 * dialect — which is exactly the sort of thin, host-specific seam the roadmap
 * says to keep at the edges.
 *
 * Run: `bun run gen:theme`
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  WHILEUI_PRESET_SOFT,
  themePresetToCssVariables,
  type ThemePreset,
} from '../../../packages/ui/src/lib/theme-presets';

const PRESET: ThemePreset = WHILEUI_PRESET_SOFT;

const here = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(here, '../src/theme.generated.css');

/** Tailwind reads `--color-*` to build utilities; `--app-color-*` is the mirror
 *  JS helpers read. Split them so only the former lands in `@theme`. */
function partition(vars: Record<string, string>) {
  const theme: Record<string, string> = {};
  const app: Record<string, string> = {};
  for (const [name, value] of Object.entries(vars)) {
    (name.startsWith('--app-') ? app : theme)[name] = value;
  }
  return { theme, app };
}

const render = (vars: Record<string, string>, indent: string) =>
  Object.entries(vars)
    .map(([name, value]) => `${indent}${name}: ${value};`)
    .join('\n');

const { light, dark, visual } = themePresetToCssVariables(PRESET);
const lightSplit = partition(light);
const darkSplit = partition(dark);

const css = `/* GENERATED by scripts/gen-theme.ts — do not edit.
   Preset: ${PRESET.name} — ${PRESET.description}
   Regenerate with: bun run gen:theme */

@theme {
  /* Visual tokens. Emitted unitless on purpose — the native track consumes them
     as numbers. On the DOM every pixel token needs calc(var(--x) * 1px); see
     packages/ui/src/web/lib/recipes.ts. */
${render(visual, '  ')}

  /* Light is the default theme; .dark overrides below. */
${render(lightSplit.theme, '  ')}
}

@layer base {
  :root {
${render(lightSplit.app, '    ')}
  }

  .dark {
${render(darkSplit.theme, '    ')}
${render(darkSplit.app, '    ')}
  }
}
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, css, 'utf8');

const count = Object.keys(visual).length + Object.keys(light).length;
console.log(`theme.generated.css written — preset "${PRESET.name}", ${count} variables`);
